[package]
name = "dram"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }

[lints.rust]
unused_imports = "allow"

[unstable]
min-publish-age = true

[registry]
global-min-publish-age = "3 days"
